name:                stenford-nn-haskell
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  stenford-nn-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stenford-nn-haskell
    - zlib
    - bytestring
    - random

tests:
  stenford-nn-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stenford-nn-haskell
